name: Clean workflow

# Controls when the workflow will run
on: 
  workflow_dispatch:
jobs:
  job_one:
    name: Clean
    runs-on: Ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            unalias rm
            rm -rf terpsite
